CLASS zbp_r_rap100_travel_m DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_rap100_travel_m .
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_rap100_travel_m IMPLEMENTATION.
ENDCLASS.
